id: ADC3A77A1
title: Prayer to Shechen Kongtrul as Vajrasattva
type: translation
pechas:
- I11F22122
- IEC57CCA1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:32.942301
  last_modified_at: 2023-01-04 12:55:32.942305
  collections:
  - Khenpo Tsöndrü Series
  - Works of Tibetan Masters
alignment_to_base:
  I11F22122/2CE0: 1D37
  IEC57CCA1/2034: 1D37
